// Compiled from the PDGA Course Directory, OpenStreetMap, and operator websites.
export const DATA_UPDATED = '2026-09-23';

export const PEORIA = { lat: 40.6936, lng: -89.589, label: 'downtown Peoria' };

export const DIFFICULTY = {
  1: { label: 'Beginner', blurb: 'Short, forgiving, great for a first round or a quick nine.' },
  2: { label: 'Casual', blurb: 'Friendly distances with a few features that ask for real shots.' },
  3: { label: 'Intermediate', blurb: 'Tight lines, meaningful elevation or length. Bring a full bag.' },
  4: { label: 'Advanced', blurb: 'Long, hilly, heavily wooded. Mistakes get punished.' },
  5: { label: 'Championship', blurb: 'Pro-tour caliber. Expect to lose a disc and love it anyway.' },
};

const pdga = (slug) => ({ label: 'PDGA listing', url: `https://www.pdga.com/course-directory/course/${slug}` });
const PFC = { label: 'Peoria Frisbee Club', url: 'https://www.facebook.com/groups/peoriafrisbeeclub/' };
const TYPICAL = { text: 'Park hours (typically dawn to dusk)', verified: false };

export const COURSES = [
  {
    id: 'bradley-park',
    name: 'Bradley Park',
    city: 'Peoria',
    address: '1300 N Park Rd, Peoria, IL 61606',
    lat: 40.706272, lng: -89.622478,
    holes: 18, established: 1984, lengthFt: 4888, altLengthFt: 5823,
    holeMix: [12, 5, 1], difficulty: 2,
    elevation: 'Two terraces', foliage: 'Mixed', tags: ['water'],
    targets: 'Mach III', tees: 'Concrete', designer: null,
    operator: 'Peoria Park District', phone: '309-682-6684',
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: true, camping: false },
    rating: { score: 3.5, votes: 2 },
    description: "Peoria's classic in-town course, laid out across two terraces of a 140-acre park next to Bradley University. Roads are out of bounds on the front nine and a creek guards the back. Every hole has two pin positions, with a fair split of left- and right-handed lines.",
    directions: 'From I-74 take exit 91 north on University St, turn left on Nebraska Ave, then left on Park Rd. Use the second park entrance on the left, then take the second left inside the park.',
    notes: ['Two pin placements on every hole', 'Park also has a dog park, playgrounds and public restrooms'],
    links: [pdga('bradley-park'), { label: 'Peoria Park District', url: 'https://www.peoriaparks.org/bradley-park/' }, PFC],
  },
  {
    id: 'creve-coeur',
    name: 'Creve Coeur Disc Golf Course',
    city: 'Creve Coeur',
    address: '586 Groveland Ave, Creve Coeur, IL 61610',
    lat: 40.6405837, lng: -89.5848366,
    holes: 9, established: 2015, lengthFt: 2507, altLengthFt: null,
    holeMix: [7, 1, 1], difficulty: 1,
    elevation: '50/50 flat and hills', foliage: 'Mixed trees and open', tags: [],
    targets: 'DISCatcher', tees: 'Concrete', designer: 'Stasz, Gebbinc & Connor',
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: null, camping: false },
    rating: null,
    description: 'A compact nine behind the Creve Coeur Community Center that mixes open shots with tree-lined fairways and a bit of elevation. Good for a quick loop or a first-ever round.',
    directions: 'At the southeast end of town where Groveland Rd meets La Rosh Ct. The first tee is behind the community center.',
    notes: [],
    links: [pdga('creve-coeur-dgc')],
  },
  {
    id: 'brady-park',
    name: 'Brady Park',
    aka: 'Cole Hollow Monster',
    city: 'East Peoria',
    address: '1800 Cole St, East Peoria, IL 61611',
    lat: 40.6427952, lng: -89.5693458,
    holes: 18, established: 2024, lengthFt: null, altLengthFt: null,
    holeMix: null, difficulty: 4,
    elevation: 'Hilly hollows', foliage: 'Heavily wooded', tags: ['wooded', 'hilly', 'water'],
    targets: null, tees: null, designer: null,
    operator: 'Fon du Lac Park District', phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: false, teeSigns: false, accessible: null, camping: false },
    rating: null,
    description: "One of the area's newest courses: a heavily wooded layout that follows Coal Creek through the hollows of Brady Park. Locals advise bringing hiking boots. It's a Ledgestone Open course, maintained by Ledgestone Disc Golf together with the Fon du Lac Park District.",
    directions: 'Brady Park is at 1800 Cole St in East Peoria. Extra parking is available along the road during events.',
    notes: ['Serious climbs, so wear real shoes'],
    links: [
      pdga('brady-park'),
      { label: 'UDisc', url: 'https://udisc.com/courses/brady-park-cole-hollow-monster-Zn92' },
      { label: 'Ledgestone Open', url: 'https://ledgestoneopen.com/courses/brady-park' },
      { label: 'Fon du Lac Park District', url: 'https://fondulacpark.com/' },
    ],
  },
  {
    id: 'icc',
    name: 'Illinois Central College',
    city: 'East Peoria',
    address: 'College Dr, East Peoria, IL',
    lat: 40.71132, lng: -89.508637,
    holes: 18, established: 2005, lengthFt: 4086, altLengthFt: 5270,
    holeMix: [15, 2, 1], difficulty: 3,
    elevation: 'Ravines', foliage: 'Tightly wooded', tags: ['wooded', 'hilly'],
    targets: 'DISCatcher', tees: 'Concrete', designer: null,
    operator: 'Illinois Central College', phone: '309-694-5790',
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: false, teeSigns: true, accessible: false, camping: false },
    rating: null,
    description: 'Tight, wooded fairways run along the edges of deep ravines on the ICC campus. It looks short on paper, but precision beats power on nearly every hole.',
    directions: 'From I-74 take exit 95B to IL-116 east, then merge onto US-24 east. Turn right at the light at the top of the hill; the course is immediately on the right.',
    notes: ['Park in the designated lot. No parking on the grass by the course.'],
    links: [pdga('illinois-central-college-disc-golf-course'), PFC],
  },
  {
    id: 'marquette-heights',
    name: 'Marquette Heights Park',
    city: 'Marquette Heights',
    address: '422 LaSalle Blvd, Marquette Heights, IL 61554',
    lat: 40.6201, lng: -89.60815,
    holes: 9, established: 1980, lengthFt: 2491, altLengthFt: null,
    holeMix: [8, 1, 0], difficulty: 1,
    elevation: 'Some low hills', foliage: 'Mixed trees and open', tags: ['open'],
    targets: 'Mach V', tees: 'Concrete', designer: 'Rob Scroggs & Eagle Scouts',
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false, cartFriendly: 'Somewhat' },
    rating: null,
    description: 'The oldest course listed in the area, built in 1980 with help from local Eagle Scouts. A short nine that blends open and wooded fairways, with some very scenic pin placements.',
    directions: 'From I-474 take IL-29 south and turn left on LaSalle Blvd. The park is half a mile ahead on the right.',
    notes: [],
    links: [pdga('marquette-heights-park'), PFC],
  },
  {
    id: 'limestone-hs',
    name: 'Limestone Community High School',
    city: 'Bartonville',
    address: '4201 S Airport Rd, Bartonville, IL 61607',
    lat: 40.641429, lng: -89.680735,
    holes: 9, established: 2007, lengthFt: null, altLengthFt: null,
    holeMix: [4, 5, 0], difficulty: 1,
    elevation: 'Flat', foliage: 'Very open', tags: ['open'],
    targets: 'Homemade', tees: 'Grass', designer: null,
    operator: 'Limestone Community High School', phone: '309-697-6271',
    access: 'public', price: 0, fee: 'Free',
    hours: { text: 'Closed during school hours and athletic events', verified: true, source: 'PDGA' },
    amenities: { restrooms: true, teeSigns: false, accessible: false, camping: false },
    rating: null,
    description: "A very open, beginner-friendly nine that weaves between the school's athletic fields, with grass tees and homemade targets.",
    directions: 'Park by the tennis courts. The first tee is between the baseball field and the tennis courts.',
    notes: ['Play only outside school hours and when no games are happening'],
    links: [pdga('limestone-community-high-school')],
  },
  {
    id: 'alpha-park',
    name: 'Alpha Park',
    city: 'Bartonville',
    address: 'Airport Rd, Bartonville, IL 61607',
    lat: 40.6388446, lng: -89.6804033,
    holes: 9, established: 2017, lengthFt: 5279, altLengthFt: null,
    holeMix: [0, 1, 8], difficulty: 3,
    elevation: '50/50 flat and hills', foliage: 'Mixed trees and open', tags: ['hilly', 'open'],
    targets: 'Mach III', tees: 'Natural', designer: null,
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: false, accessible: null, camping: false, cartFriendly: 'Somewhat' },
    rating: null,
    description: 'Only nine holes, but eight of them stretch past 400 feet. A long, well-kept layout with plenty of elevation that rewards a big arm.',
    directions: 'From I-474 take exit 5 and head south on Airport Rd about 2 miles to the park entrance on the left. Park by the shelters; the first tee is next to the swings.',
    notes: [],
    links: [pdga('alpha-park')],
  },
  {
    id: 'megiddo',
    name: 'Megiddo Disc Golf Course',
    city: 'Morton',
    address: '2309 Veterans Rd, Morton, IL 61550',
    lat: 40.6414638, lng: -89.4809625,
    holes: 18, established: 2014, lengthFt: 5593, altLengthFt: 6609,
    holeMix: [10, 5, 3], difficulty: 4,
    elevation: 'Mostly hilly', foliage: 'Woodsy', tags: ['wooded', 'hilly', 'water'],
    targets: 'Mach III with Trapper baskets', tees: 'Concrete', designer: 'Kip Taufer',
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: 'Seasonal', teeSigns: false, accessible: null, camping: false },
    rating: { score: 4.25, votes: 4 },
    description: 'A Kip Taufer design that plays in and around three ravines with creeks throughout. There are no wide-open holes; every shot needs a line.',
    directions: 'From I-74 take exit 102 north on Morton Ave, turn left on Courtland Ave, then right on Veterans Rd. The course is in the woods behind the ballfield parking lot.',
    notes: ['Restrooms available except in winter', 'Concessions open during baseball season'],
    links: [pdga('megiddo-disc-golf-course'), { label: 'Course Facebook group', url: 'https://www.facebook.com/groups/146978418844162/' }],
  },
  {
    id: 'mcnaughton-park',
    name: 'McNaughton Park',
    city: 'Pekin',
    address: '298 McNaughton Park Dr, Pekin, IL 61554',
    lat: 40.594017, lng: -89.600683,
    holes: 18, established: 1992, lengthFt: 6205, altLengthFt: 7127,
    holeMix: [8, 7, 3], difficulty: 4,
    elevation: 'All hilly', foliage: 'Woodsy', tags: ['wooded', 'hilly'],
    targets: 'Mach III', tees: 'Concrete', designer: null,
    operator: 'Pekin Park District', phone: '309-347-7275',
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: false, teeSigns: true, accessible: false, camping: false },
    rating: { score: 4, votes: 4 },
    description: 'A hilly championship course inside an 850-acre nature park with two lakes, a waterfall, horse trails and teepee shelters. Expect lots of trees, thick rough and dual tees.',
    directions: 'From I-474 take exit 9 to IL-29 south, then turn left on IL-98. Go about 2 miles to the top of the hill (a mile past Parkway Dr) and turn right into the park.',
    notes: ['Alcohol, off-leash dogs and leaving designated trails are prohibited in the park'],
    links: [pdga('mcnaughton-park'), { label: 'Pekin Park District', url: 'https://www.pekinparkdistrict.org/mcnaughton-park' }, PFC],
  },
  {
    id: 'tuscarora',
    name: 'Tuscarora Park',
    city: 'Peoria (Hollis)',
    address: '5624 W Tuscarora Rd, Peoria, IL 61607',
    lat: 40.6075982, lng: -89.6839976,
    holes: 18, established: 2016, lengthFt: 2695, altLengthFt: null,
    holeMix: null, difficulty: 3,
    elevation: 'Mostly hilly', foliage: 'Woodsy', tags: ['wooded', 'hilly', 'water'],
    targets: 'Mach III', tees: 'Rubber', designer: 'Johnnie Harrison & Kip Taufer',
    operator: 'Hollis Park District', phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: { text: '8:00 AM to dusk', open: '08:00', close: 'sunset', verified: true, source: 'Hollis Park District' },
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: null,
    description: "Built in two phases (nine holes in 2016, nine more in 2018). Three scenic holes sit on top of Reeder's Knob; the rest climb through hills and trees across an out-of-bounds creek. Short, but full of elevation and tough pins.",
    directions: 'Take US-24 to Tuscarora Rd and go about 2 miles. The course is on the left just past Hollis Grade School. Park near the pavilion; the first tee is between the first-base line and the playground.',
    notes: ['Alcohol is prohibited on Hollis Park District property', 'Park district lists a total course distance of about 2,695 ft'],
    links: [
      pdga('tuscarora-disc-golf-course'),
      { label: 'Hollis Park District', url: 'https://www.hollispark.org/tuscarora-disc-golf-course' },
      { label: 'Course Facebook', url: 'https://www.facebook.com/tuscaroradiscgolf/' },
    ],
  },
  {
    id: 'northwood-blue',
    name: 'Northwood Park: Blue',
    city: 'Morton',
    address: '22216 N Main St, Morton, IL 61550',
    lat: 40.648133, lng: -89.45105,
    holes: 18, established: 2002, lengthFt: 5943, altLengthFt: null,
    holeMix: [9, 5, 4], difficulty: 4,
    elevation: '50/50 flat and hills', foliage: 'Wooded corridors', tags: ['wooded', 'hilly'],
    targets: 'DISCatcher', tees: 'Concrete', designer: 'Greg Nettles',
    operator: 'Morton Park District', phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: { text: 'Sunrise to 11:00 PM', open: 'sunrise', close: '23:00', verified: true, source: 'OpenStreetMap' },
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: { score: 4.6, votes: 5 },
    description: "Morton's much-loved original: flat and hilly wooded corridors that call for every kind of shot, finishing with two of the best closing holes around. Among the area's PDGA listings with several reviews, it has the highest rating.",
    directions: 'From I-74 take exit 102B north on Morton Ave, turn right on Courtland, then left on N Main St. The park entrance is about a mile ahead on the right, at the curve.',
    notes: ['The entry gate is closed November through March. Park at the entrance and walk in.'],
    links: [
      pdga('northwood-park'),
      { label: 'UDisc', url: 'https://udisc.com/courses/northwood-park-blue-igUY' },
      { label: 'Course map', url: 'https://morton.recdesk.com/RecDeskPortal/Portals/159/Northwood%20Park%20Blue%20Disc%20Golf%20Course%20Layout%20July%202021.png' },
      { label: 'Morton Park District', url: 'https://morton.recdesk.com/Community/Facility/Detail?facilityId=8' },
      PFC,
    ],
  },
  {
    id: 'northwood-black',
    name: 'Northwood Park: Black',
    city: 'Morton',
    address: '22216 N Main St, Morton, IL 61550',
    lat: 40.6496935, lng: -89.4460848,
    holes: 18, established: 2021, lengthFt: 10500, altLengthFt: null, par: 68,
    holeMix: null, difficulty: 5,
    elevation: 'Significant elevation', foliage: 'Wooded, generous fairways', tags: ['wooded', 'hilly'],
    targets: 'Mach X', tees: 'Concrete', designer: 'Kip Taufer',
    operator: 'Morton Park District', phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: { text: 'Sunrise to 11:00 PM', open: 'sunrise', close: '23:00', verified: true, source: 'OpenStreetMap' },
    amenities: { restrooms: true, teeSigns: true, accessible: null, camping: false },
    rating: null,
    description: 'Built from the Gold layout made famous at the 2019 PDGA Pro Worlds, Black is a roughly 10,500-foot, par-68 monster with three par 5s, several bridges and serious elevation. The fairways are generous for a wooded course, but it tests every part of your game. It\'s a featured Ledgestone Open course.',
    directions: 'Same park as Northwood Blue: from I-74 exit 102B go north on Morton Ave, right on Courtland, left on N Main St, then about a mile to the park entrance on the right.',
    notes: ['The entry gate is closed November through March. Park at the entrance and walk in.', 'Nearly 2 miles of walking from the long tees'],
    links: [
      pdga('northwood-black'),
      { label: 'UDisc', url: 'https://udisc.com/courses/northwood-park-black-uqNc' },
      { label: 'Course map', url: 'https://morton.recdesk.com/RecDeskPortal/Portals/159/Northwood%20Park%20Black%20Disc%20Golf%20Course%20Layout%20July%202021.png' },
      { label: 'Morton Park District', url: 'https://morton.recdesk.com/Community/Facility/Detail?facilityId=8' },
    ],
  },
  {
    id: 'wildlife-prairie',
    name: 'Wildlife Prairie Park',
    city: 'Hanna City',
    address: '3826 N Taylor Rd, Hanna City, IL 61536',
    lat: 40.735381, lng: -89.747164,
    holes: 18, established: 2010, lengthFt: 5268, altLengthFt: 8828,
    holeMix: [10, 4, 4], difficulty: 5,
    elevation: 'All hilly', foliage: 'Woodsy', tags: ['wooded', 'hilly', 'water'],
    targets: 'Chainstar', tees: 'Concrete (dual)', designer: 'Brian Lucas',
    operator: 'Wildlife Prairie Park', phone: '309-676-0998',
    access: 'pay', price: 17, fee: 'Park admission: $17 adults (13+), $12 kids (3 to 12). Memberships $85 individual / $125 family.',
    hours: { text: 'Dawn to dusk, daily', open: 'sunrise', close: 'sunset', verified: true, source: 'Wildlife Prairie Park' },
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: null,
    description: 'A championship-level course winding through the hilly, wooded west side of Wildlife Prairie Park. Big elevation changes, Kickapoo Creek and three lakes (three holes carry over water) with hole lengths from about 200 ft on the whites to nearly 1,000 ft on the golds. There is also an Executive 9 layout.',
    directions: 'From I-74 take exit 82 (Kickapoo/Edwards) and head south about 3 miles through the four-way stop, where the road becomes Taylor Rd. The course is on the right, across from the park\'s Main Gate.',
    notes: ['Pay cash at the kiosk by the first tee, or by card at the Main Gate', 'Admission also covers hiking, fishing, biking and the animal trails', 'The park posts periodic course closings on its website'],
    links: [pdga('wildlife-prairie-park'), { label: 'Wildlife Prairie Park', url: 'https://wildlifeprairiepark.org/recreation/disc-golf' }],
  },
  {
    id: 'northwoods-church',
    name: 'Northwoods Community Church',
    city: 'Peoria',
    address: '10700 N Allen Rd, Peoria, IL 61615',
    lat: 40.8177573, lng: -89.629683,
    holes: 9, established: 2015, lengthFt: 2846, altLengthFt: 2759,
    holeMix: [3, 6, 0], difficulty: 1,
    elevation: 'Flat', foliage: 'Sparse', tags: ['open', 'water'],
    targets: 'Mach III', tees: 'Concrete', designer: 'Steve Hollaway',
    operator: 'Northwoods Community Church', phone: null,
    access: 'private', price: 0, fee: 'No fee listed',
    hours: { text: 'Not listed. Private church property.', verified: false },
    amenities: { restrooms: false, teeSigns: false, accessible: null, camping: false },
    rating: null,
    description: 'A flat, open recreational nine on church grounds, with water in play on a few holes.',
    directions: 'Take IL-6 north to exit 5 (Allen Rd) and turn left. Continue straight through the traffic circle; the church is 0.4 mile ahead on the right.',
    notes: ['Private property. Be respectful and avoid service times.'],
    links: [pdga('northwoods-community-church')],
  },
  {
    id: 'kennel-lake',
    name: 'Kennel Lake',
    city: 'Morton',
    address: '22172 Kennel Lake Ln, Morton, IL 61550',
    lat: 40.6462703, lng: -89.4230038,
    holes: 18, established: 2015, lengthFt: 5710, altLengthFt: null,
    holeMix: [10, 4, 4], difficulty: 3,
    elevation: '50/50 flat and hills', foliage: 'Stands of trees', tags: ['water'],
    targets: 'Discraft', tees: 'Artificial turf', designer: 'Nate Heinold & Kip Taufer',
    operator: "Kennel Lake Sportsmen's Club", phone: '309-266-9641',
    access: 'pay', price: 5, fee: '$5 per round for guests; club members play free',
    hours: { text: 'Members and paying guests', verified: false },
    amenities: { restrooms: true, teeSigns: true, accessible: null, camping: true },
    rating: null,
    description: "Loops around a small private lake at a camping and sportsman's club. Open to club members and to guests who pay per round.",
    directions: 'From I-74 take exit 102A north on Morton Ave, then turn right on E Lakeland Rd. After about 1.4 miles Lakeland turns left and becomes Hirstein Rd; turn right to rejoin Lakeland Rd, go one mile, then turn left on Kennel Lake Ln.',
    notes: ['Private club. Guests pay per round.'],
    links: [pdga('kennel-lake'), { label: "Kennel Lake Sportsmen's Club", url: 'http://www.kennellake.com/' }],
  },
  {
    id: 'washington-park',
    name: 'Washington Park',
    city: 'Washington',
    address: 'Lincoln St & Wilshire Dr, Washington, IL 61571',
    lat: 40.7127156, lng: -89.4118444,
    holes: 18, established: 1998, lengthFt: 5658, altLengthFt: 5835,
    holeMix: [10, 6, 2], difficulty: 3,
    elevation: 'Mild hills', foliage: 'Fairly open', tags: ['open'],
    targets: 'DISCatcher', tees: 'Concrete', designer: null,
    operator: 'Washington Park District', phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: true, camping: false },
    rating: { score: 2.75, votes: 4 },
    description: 'A pretty neighborhood-park course with mature trees and gentle slopes. It is fairly open but long, so wind is a big factor. It hosts Ledgestone amateur play along with local school and park district events.',
    directions: 'From US-24 and IL-116 in East Peoria, go east on US-24 about 6.5 miles. Turn south on N Main St, right on Devonshire, left on Wilshire, then left on Lincoln. Use the first lot on the right.',
    notes: ['Open fairways make wind the real opponent here'],
    links: [
      pdga('washington-park'),
      { label: 'UDisc', url: 'https://udisc.com/courses/washington-park-lvEf' },
      { label: 'Washington Park District', url: 'https://www.washingtonparkdistrict.com/parks-facilities/washington-park' },
      PFC,
    ],
  },
  {
    id: 'sunset-hills',
    name: 'Sunset Hills',
    city: 'Pekin',
    address: '1620 Summit Dr, Pekin, IL 61554',
    lat: 40.5433322, lng: -89.6129335,
    holes: 18, established: 2014, lengthFt: 7240, altLengthFt: 8834,
    holeMix: [4, 8, 6], difficulty: 4,
    elevation: 'Rolling', foliage: 'Mixed trees and open', tags: ['water', 'open'],
    targets: 'DISCatcher Pro', tees: 'Mixed', designer: 'Seth Friedrich',
    operator: 'Sunset Hills Golf Club', phone: '309-347-7553',
    access: 'pay', price: 21, fee: '$21 day pass per person, cart included (pro shop)',
    hours: { text: 'Check in at the pro shop. Call ahead during ball golf season.', verified: false },
    amenities: { restrooms: true, teeSigns: true, accessible: null, camping: false, cartFriendly: 'Carts provided' },
    rating: { score: 5, votes: 1 },
    description: 'Shares its land with Sunset Hills Golf Club: the front 10 play on the ball golf course and the back 8 on the property next door. Risk versus reward shows up on every hole, with lots of water and OB. There is a pro shop, locker rooms and a bar & grill on site.',
    directions: 'From Court St (IL-9) in Pekin, go south on Valle Vista Blvd and turn left into Sunset Hills Golf Club about 300 ft past the stop sign. Park in the lower lot. The pro shop is on the lower level and the first tee is off the back deck.',
    notes: ['Players must check in at the pro shop before teeing off', 'Reserve a tee time during ball golf season', 'Yearly memberships available'],
    links: [
      pdga('sunset-hills-dgc'),
      { label: 'Sunset Hills Golf Club', url: 'https://sunsethillsgc.com/disc-golf/' },
      { label: 'UDisc', url: 'https://udisc.com/courses/sunset-hills-dyW0' },
    ],
  },
  {
    id: 'three-sisters',
    name: 'Three Sisters Park',
    city: 'Chillicothe',
    address: '17189 N Route 29, Chillicothe, IL 61523',
    lat: 40.8929759, lng: -89.5038611,
    holes: 18, established: 2018, lengthFt: 5775, altLengthFt: null,
    holeMix: [10, 7, 1], difficulty: 3,
    elevation: 'Rolling', foliage: 'Woodsy', tags: ['wooded'],
    targets: 'Baskets', tees: null, designer: null,
    operator: 'Three Sisters Park', phone: null,
    access: 'private', price: 0, fee: 'No fee listed',
    hours: { text: 'Closed periodically for park events', verified: true, source: 'PDGA' },
    amenities: { restrooms: false, teeSigns: true, accessible: true, camping: true, cartFriendly: 'Very' },
    rating: null,
    description: 'A wooded, moderate-length course on private park grounds, and very cart-friendly.',
    directions: 'From Peoria take IL-29 north about 13 miles and turn left onto Hamm\'s Crossing. After 0.3 mile turn right into the park, pass the big round red barn and park on the left by the warehouse.',
    notes: ['Private property that closes for events. Check before you go.'],
    links: [pdga('three-sisters-park')],
  },
  {
    id: 'shore-acres',
    name: 'Shore Acres Park',
    city: 'Chillicothe',
    address: '100 Park Blvd, Chillicothe, IL 61523',
    lat: 40.904841, lng: -89.489602,
    holes: 9, established: 1996, lengthFt: 5397, altLengthFt: null,
    holeMix: [9, 8, 1], difficulty: 2,
    elevation: 'Mostly flat, a few hills', foliage: 'Stands of trees', tags: ['wooded'],
    targets: 'Mach III', tees: 'Concrete (dual)', designer: null,
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: { score: 2.5, votes: 2 },
    description: 'A short, lightly wooded nine with a few hills. Two tees per basket let you play a full 18, and there is a putting green.',
    directions: 'Take IL-29 north into Chillicothe and turn right on Cloverdale Rd at the first light. Cross the tracks and turn right on River Birch Dr; the park is on the left.',
    notes: ['9 baskets with dual tees, so you can play 18', 'Putting green on site'],
    links: [pdga('shore-acres-park')],
  },
  {
    id: 'mackinaw',
    name: 'Westwood Park',
    city: 'Mackinaw',
    address: '301 W 2nd St, Mackinaw, IL 61755',
    lat: 40.530997, lng: -89.362308,
    holes: 9, established: 2016, lengthFt: 2569, altLengthFt: null,
    holeMix: [5, 4, 0], difficulty: 2,
    elevation: 'Rolling', foliage: 'Mixed trees and open', tags: [],
    targets: 'Chainstar', tees: null, designer: null,
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: null,
    description: 'A small-town nine that calls for a variety of shots and makes good use of elevation and big, mature trees.',
    directions: 'Head east on IL-9, turn north on Mackinaw Rd, then west on 2nd St and follow the signs to Westwood Park.',
    notes: [],
    links: [pdga('mackinaw-dgc-westood')],
  },
  {
    id: 'lake-eureka',
    name: 'Lake Eureka',
    city: 'Eureka',
    address: 'Milt & Lynn Hinnen Way, Eureka, IL 61530',
    lat: 40.70466, lng: -89.275329,
    holes: 18, established: 2004, lengthFt: 4815, altLengthFt: null,
    holeMix: [15, 1, 2], difficulty: 3,
    elevation: 'A few hills', foliage: 'Tightly wooded', tags: ['wooded', 'water'],
    targets: 'DISCatcher', tees: 'Concrete', designer: null,
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: TYPICAL,
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: { score: 4.2, votes: 5 },
    description: 'Tightly wooded, with several long open holes and a few hills, set in a beautiful park around a large lake.',
    directions: 'From I-74 take exit 112 (IL-117) north 5 miles to Eureka. Turn left on Lake Rd, then take the first right into the park. The first tee is by the shelters across from the ball diamond.',
    notes: [],
    links: [pdga('lake-eureka-disc-golf-course')],
  },
  {
    id: 'goodfield',
    name: 'Goodfield Park',
    city: 'Goodfield',
    address: '532 E Robinson St, Goodfield, IL 61742',
    lat: 40.630988, lng: -89.26655,
    holes: 9, established: 2017, lengthFt: 2191, altLengthFt: null,
    holeMix: [9, 0, 0], difficulty: 1,
    elevation: 'Rolling', foliage: 'Scattered oaks', tags: ['open'],
    targets: 'Mach III', tees: 'Concrete (dual)', designer: null,
    operator: null, phone: null,
    access: 'public', price: 0, fee: 'Free',
    hours: { text: '5:00 AM to 10:00 PM', open: '05:00', close: '22:00', verified: true, source: 'OpenStreetMap' },
    amenities: { restrooms: true, teeSigns: true, accessible: false, camping: false },
    rating: null,
    description: 'A short, fairly open nine where mature oaks come into play. Every hole except #1 has dual tees.',
    directions: 'From I-74 take exit 112 and go north on IL-117 half a mile, then turn right on E Robinson St and follow it to the dead end at the park.',
    notes: [],
    links: [pdga('goodfield-park')],
  },
  {
    id: 'camp-kearney',
    name: 'Camp Kearney',
    city: 'Canton',
    address: '30000 Mission Camp Rd, Canton, IL 61520',
    lat: 40.5447616, lng: -89.8726735,
    holes: 18, established: 2021, lengthFt: null, altLengthFt: null,
    holeMix: null, difficulty: 3,
    elevation: 'Varied', foliage: 'Open, wooded and waterside', tags: ['wooded', 'water', 'open'],
    targets: 'ChainStar Pro', tees: 'Mixed', designer: 'Arin Haven',
    operator: 'South Side Mission', phone: null,
    access: 'private', price: 0, fee: 'No fee listed',
    hours: { text: 'Private camp. Confirm access before visiting.', verified: false },
    amenities: { restrooms: false, teeSigns: false, accessible: null, camping: null },
    rating: null,
    description: "An 18-hole course at South Side Mission's church camp, on a beautiful property with a good mix of open, wooded and waterside holes. The holes look short, but you'll have to scramble once you leave the fairway.",
    directions: 'Mission Camp Rd, east of Canton.',
    notes: ['Private camp property. Get permission before you play.'],
    links: [pdga('camp-kearney')],
  },
];
